---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: label-patcher
  namespace: {{ include "uday-app.namespace" . }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: label-patcher
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: label-patcher
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-9"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: label-patcher
subjects:
- kind: ServiceAccount
  name: label-patcher
  namespace: {{ include "uday-app.namespace" . }}

---
apiVersion: batch/v1
kind: Job
metadata:
  name: apply-namespace-labels-{{ randAlphaNum 5 | lower }}
  namespace: {{ include "uday-app.namespace" . }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: label-patcher
      containers:
      - name: labeler
        image: bitnami/kubectl:latest
        command:
        - /bin/sh
        - -c
        - |
          set -e
          NAMESPACE="{{ include "uday-app.namespace" . }}"
          echo "Aplicando labels no namespace $NAMESPACE..."
          kubectl patch namespace $NAMESPACE \
            -p '{"metadata":{"labels":{"enviroment":"development","istio-injection":"enabled"}}}'
          echo "Labels aplicadas com sucesso!"
          kubectl get namespace $NAMESPACE -o jsonpath='{.metadata.labels}' | grep istio-injection

