apiVersion: v1
kind: Secret
metadata:
  name: nexus-registry-secret
  namespace: {{ include "uday-app.namespace" . }}
  labels:
    app: registry
type: kubernetes.io/dockercfg
data:
  .dockercfg: {{ .Values.registry.dockercfg }}
