apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ include "uday-app.namespace" . }}
  labels:
    app: deployment
imagePullSecrets:
- name: nexus-registry-secret
