apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.postgres.name }}
  namespace: {{ include "uday-app.namespace" . }}
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_USER: {{ .Values.secrets.postgres.data.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.data.POSTGRES_PASSWORD }}
  POSTGRES_DB: {{ .Values.secrets.postgres.data.POSTGRES_DB }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.backend.name }}
  namespace: {{ include "uday-app.namespace" . }}
  labels:
    app: backend
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.backend.data.SECRET_KEY }}
  DATABASE_URL: {{ .Values.secrets.backend.data.DATABASE_URL }}
