apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.postgres.name }}
  namespace: {{ include "uday-app.namespace" . }}
  labels:
    app: postgres
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.postgres.size }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistence.uploads.name }}
  namespace: {{ include "uday-app.namespace" . }}
  labels:
    app: backend
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.uploads.size }}
