services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=user 
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=appdb
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d appdb"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  migration:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: migration
    entrypoint: sh -c "alembic upgrade head && exit 0"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:senha123@postgres:5432/appdb

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - dados_imagem:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:senha123@postgres:5432/appdb
      - SECRET_KEY=${SECRET_KEY:-chavejwtsecreta}
      - JWT_ALGORITHM=HS256
      - JWT_EXPIRATION_TIME=30
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "80:80"
    volumes:
      - dados_html:/usr/share/nginx/html
    depends_on:
      - backend
    environment:
      - BACKEND_HOST=backend

volumes:
  postgres_data:
  dados_imagem:
  dados_html:
  