# Service Account para deployments com acesso ao registry privado
apiVersion: v1
kind: ServiceAccount
metadata:
  name: deployer-sa
  namespace: uday-app
  labels:
    app: deployment
imagePullSecrets:
- name: nexus-registry-secret