# Secret para credenciais do PostgreSQL
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: uday-app
  labels:
    app: postgres
type: Opaque
data:
  # Valores codificados em base64
  # user       = base64("user")
  # senha123   = base64("senha123")
  # appdb      = base64("appdb")
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD: c2VuaGExMjM=
  POSTGRES_DB: YXBwZGI=

  # Para gerar novos valores em base64:
  # echo -n "seu_valor" | base64

---
# Secret para JWT do Backend e conexão com o banco de dados
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: uday-app
  labels:
    app: backend
type: Opaque
data:
  # chavejwtsecreta = base64("chavejwtsecreta")
  SECRET_KEY: Y2hhdmVqd3RzZWNyZXRh

  # postgresql+psycopg2://user:senha123@postgres-service:5432/appdb
  # = base64("postgresql+psycopg2://user:senha123@postgres-service:5432/appdb")
  DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnMjovL3VzZXI6c2VuaGExMjNAcG9zdGdyZXMtc2VydmljZTo1NDMyL2FwcGRi

  # Para ambientes de produção, gere uma chave segura:
  # python -c "import secrets; print(secrets.token_urlsafe(32))" | base64